# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

git:
  depth: 10

language: node_js

node_js:
  - "iojs"
  - "0.12"

script: "bundle exec jekyll build"

sudo: false
