# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

git:
  depth: 10
  # Handle git submodules yourself
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

# http://jekyllrb.com/docs/continuous-integration/

language: ruby
cache: bundler
rvm:
- 2.1
script: ./script/cibuild

# branch whitelist
#branches:
#  only:
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

#language: node_js

#node_js:
#  - "iojs"
#  - "0.12"

sudo: false
