name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments
exclude: [vendor]

copyright:
  author: Hacktoolkit
  url: http://www.hacktoolkit.com
  year: 2015

htk:
  credits: true
  mobile: true
  show_footer: true
  javascripts:

meta:
  description: Jekyll Hacktoolkit. HTML5 Boilerplate inspired. Opinionated framework.
  keywords: hacktoolkit,htk,jekyll,html5,css3

libs:
  css:
    jqueryui: 1.11.3
    pure: 0.6.0
  js:
    backbone: 1.1.2
    jquery: 2.1.3
    jqueryui: 1.11.2
    lodash: 3.4.0
    parse: 1.3.5
    yui: 3.18.1

api:
  facebook:
    app_id:
  google:
    maps:
      init: false
      key:
      sensor: true
      default_lat: -34.397
      default_lng: 150.644
      default_zoom: 8
      container: map_canvas
  parse:
    app_id:
    js_key:
  rollbar:
    access_token:

fonts:
  google: Cabin+Condensed:400,500,600,700
