name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments
exclude: [vendor]

copyright:
  author: Hacktoolkit
  url: http://www.hacktoolkit.com
  year: 2015

htk:
  credits: true

meta:
  description: Jekyll Hacktoolkit. HTML5 Boilerplate inspired. Opinionated framework.
  keywords: hacktoolkit,htk,jekyll,html5,css3

libs:
  css:
    pure: 0.6.0
  js:
    parse: 1.3.5
    yui: 3.18.1

api:
  facebook:
    app_id:
  google:
    maps:
  parse:
    app_id:
    js_key:
  rollbar:
    access_token:

fonts:
  google: Cabin+Condensed:400,500,600,700
